import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:alif_flow/models/sales_entry.dart';
import 'package:alif_flow/utils/ui_helpers.dart';

class PdfReportService {
  /// Generate and show print/share dialog for a weekly report.
  Future<void> generateAndPrintReport({
    required List<SalesEntry> salesEntries,
    required List<ProductMovementEntry> movementEntries,
    required double totalSales,
    required double totalReceived,
    required double totalBalance,
    String sellerName = 'Seller',
    String? reportDate,
  }) async {
    final pdf = pw.Document();
    final date = reportDate ?? DateTime.now().toString().split(' ')[0];

    // Group entries by category
    final Map<String, List<int>> categoryIndices = {};
    for (int i = 0; i < salesEntries.length; i++) {
      final cat = salesEntries[i].category.isNotEmpty
          ? salesEntries[i].category
          : 'other';
      categoryIndices.putIfAbsent(cat, () => []).add(i);
    }

    final categoryDisplayNames = {
      'soap': 'Soap Products',
      'special': 'Special Products',
      'paint': 'Paint Products',
    };

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        header: (context) => _buildPdfHeader(sellerName, date),
        footer: (context) => _buildPdfFooter(context),
        build: (context) {
          final widgets = <pw.Widget>[];

          // Category tables
          for (final category in categoryIndices.keys) {
            final indices = categoryIndices[category]!;
            final catSales = indices.map((i) => salesEntries[i]).toList();
            final catMovement = indices
                .map((i) => i < movementEntries.length
                    ? movementEntries[i]
                    : null)
                .toList();

            widgets.add(pw.SizedBox(height: 16));
            widgets.add(
              pw.Text(
                categoryDisplayNames[category] ?? category,
                style: pw.TextStyle(
                  fontSize: 14,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
            );
            widgets.add(pw.SizedBox(height: 8));
            widgets.add(_buildCategoryTable(catSales, catMovement));
          }

          // Grand totals
          widgets.add(pw.SizedBox(height: 24));
          widgets.add(pw.Divider(thickness: 2));
          widgets.add(pw.SizedBox(height: 8));
          widgets.add(_buildTotalRow('Gross Sales', totalSales));
          widgets.add(_buildTotalRow('Amount Received', totalReceived));
          widgets.add(pw.Divider());
          widgets.add(_buildTotalRow('Net Balance Due', totalBalance, isBold: true));

          return widgets;
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (format) async => pdf.save(),
      name: 'Alif-Flow_Weekly_Report_$date',
    );
  }

  pw.Widget _buildPdfHeader(String sellerName, String date) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'WEEKLY SALES REPORT',
                  style: pw.TextStyle(
                    fontSize: 18,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.blue800,
                  ),
                ),
                pw.SizedBox(height: 4),
                pw.Text(
                  'Alif-Flow Business',
                  style: pw.TextStyle(
                    fontSize: 12,
                    color: PdfColors.grey700,
                  ),
                ),
              ],
            ),
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                pw.Text('Seller: $sellerName', style: const pw.TextStyle(fontSize: 10)),
                pw.Text('Date: $date', style: const pw.TextStyle(fontSize: 10)),
              ],
            ),
          ],
        ),
        pw.Divider(thickness: 2, color: PdfColors.blue800),
        pw.SizedBox(height: 8),
      ],
    );
  }

  pw.Widget _buildPdfFooter(pw.Context context) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Text(
          'Generated by Alif-Flow',
          style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey500),
        ),
        pw.Text(
          'Page ${context.pageNumber} of ${context.pagesCount}',
          style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey500),
        ),
      ],
    );
  }

  pw.Widget _buildCategoryTable(
    List<SalesEntry> sales,
    List<ProductMovementEntry?> movements,
  ) {
    final headers = [
      'Product',
      'Qty',
      'Price',
      'Total',
      'Received',
      'Balance',
      'Prev',
      'Moved',
      'Added',
      'Stock',
    ];

    return pw.TableHelper.fromTextArray(
      headerStyle: pw.TextStyle(fontSize: 8, fontWeight: pw.FontWeight.bold),
      cellStyle: const pw.TextStyle(fontSize: 8),
      headerDecoration: const pw.BoxDecoration(color: PdfColors.grey200),
      cellHeight: 22,
      cellAlignments: {
        0: pw.Alignment.centerLeft,
        1: pw.Alignment.center,
        2: pw.Alignment.center,
        3: pw.Alignment.center,
        4: pw.Alignment.center,
        5: pw.Alignment.center,
        6: pw.Alignment.center,
        7: pw.Alignment.center,
        8: pw.Alignment.center,
        9: pw.Alignment.center,
      },
      headers: headers,
      data: [
        ...sales.asMap().entries.map((entry) {
          final i = entry.key;
          final s = entry.value;
          final m = i < movements.length ? movements[i] : null;
          return [
            s.productName,
            s.quantitySold > 0 ? UiHelpers.formatNumber(s.quantitySold) : '-',
            s.unitPrice > 0 ? UiHelpers.formatNumber(s.unitPrice) : '-',
            s.totalPrice > 0 ? UiHelpers.formatNumber(s.totalPrice) : '-',
            s.amountReceived > 0 ? UiHelpers.formatNumber(s.amountReceived) : '-',
            s.balanceDue != 0 ? UiHelpers.formatNumber(s.balanceDue) : '-',
            (m?.previousStock ?? 0) > 0 ? UiHelpers.formatNumber(m!.previousStock) : '-',
            (m?.productsMoved ?? 0) > 0 ? UiHelpers.formatNumber(m!.productsMoved) : '-',
            (m?.newStockAdded ?? 0) > 0 ? UiHelpers.formatNumber(m!.newStockAdded) : '-',
            (m?.currentStock ?? 0) > 0 ? UiHelpers.formatNumber(m!.currentStock) : '-',
          ];
        }),
        // Totals row
        [
          'TOTAL',
          UiHelpers.formatNumber(sales.fold<int>(0, (s, e) => s + e.quantitySold)),
          '---',
          UiHelpers.formatNumber(sales.fold<double>(0, (s, e) => s + e.totalPrice)),
          UiHelpers.formatNumber(sales.fold<double>(0, (s, e) => s + e.amountReceived)),
          UiHelpers.formatNumber(sales.fold<double>(0, (s, e) => s + e.totalPrice) -
                  sales.fold<double>(0, (s, e) => s + e.amountReceived)),
          UiHelpers.formatNumber(movements.fold<int>(0, (s, e) => s + (e?.previousStock ?? 0))),
          UiHelpers.formatNumber(movements.fold<int>(0, (s, e) => s + (e?.productsMoved ?? 0))),
          UiHelpers.formatNumber(movements.fold<int>(0, (s, e) => s + (e?.newStockAdded ?? 0))),
          UiHelpers.formatNumber(movements.fold<int>(0, (s, e) => s + (e?.currentStock ?? 0))),
        ],
      ],
    );
  }

  pw.Widget _buildTotalRow(String label, double value, {bool isBold = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 2),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            label,
            style: pw.TextStyle(
              fontSize: isBold ? 14 : 11,
              fontWeight: isBold ? pw.FontWeight.bold : pw.FontWeight.normal,
            ),
          ),
          pw.Text(
            '\$${UiHelpers.formatNumber(value)}',
            style: pw.TextStyle(
              fontSize: isBold ? 14 : 11,
              fontWeight: pw.FontWeight.bold,
              color: value > 0 ? PdfColors.red : PdfColors.green,
            ),
          ),
        ],
      ),
    );
  }
}
